### ISSUE TITLE
Page build failure???

### ISSUE THREAD

**Issue by ZeroDot1** [mikelpint/Startpage#28]
@mikelpint  I have received this e-mail: 
![bildschirmfoto_2018-03-21_16-10-25](https://user-images.githubusercontent.com/28985171/37718175-6ca3ce6a-2d22-11e8-9628-8f091cd7b7d5.png)

```
The page build failed for the `master` branch with the following error:

Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-builds/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

```

**Comment by mikelpint** [comment]
I don't think that this is a serious error. The page goes well.

It happenned to me building some pages but there was nothing suspicious in them.

**Comment by ZeroDot1** [comment]
OK, thanks, I' m closing this.
