### ISSUE TITLE
CSS Bug: The startpage is not centred

### ISSUE THREAD

**Issue by ZeroDot1** [mikelpint/Startpage#31]
If you are using a high-resolution screen, the page is not centered anymore. This doesn't look good. 
Sceenshot: 
![screencapture-mikelpint-github-io-startpage-de-html-2018-05-23-19_51_25](https://user-images.githubusercontent.com/28985171/40442219-4afd51e6-5ec3-11e8-92ea-d0dd936cfffe.png)

**Comment by mikelpint** [comment]
Which resolution are you using?

**Comment by ZeroDot1** [comment]
use the resolution: 2560x1440

**Comment by mikelpint** [comment]
I think it works now. I realized that when I create the website I set the maximun width to 2000 pixels.

**Comment by ZeroDot1** [comment]
This looks much better, perfect, I close here, the bug is fixed. 
![screencapture-mikelpint-github-io-startpage-de-html-2018-05-23-21_56_40](https://user-images.githubusercontent.com/28985171/40448013-9409ff7c-5ed4-11e8-93b3-b51dfed89467.png)
