### ISSUE TITLE
General

### ISSUE THREAD

**Issue by ZeroDot1** [mikelpint/Startpage#6]
What do you think about adding effects to the design?
Screenshot example:
![bildschirmfoto_2017-11-16_18-46-45](https://user-images.githubusercontent.com/28985171/32906854-862b3bf6-cafe-11e7-947c-f465017d374c.png)

**Comment by mikelpint** [comment]
It is a good idea. I can also add some animatons.

**Comment by ZeroDot1** [comment]
I created the effect for the search field like this.
`box-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #fff, 0 0 20px #228DFF, 0 0 35px #228DFF, 0 0 40px #228DFF, 0 0 50px #228DFF, 0 0 75px #228DFF;`

**Comment by ZeroDot1** [comment]
https://github.com/mikelpint/Startpage/pull/7

**Comment by ZeroDot1** [comment]
If you move your mouse over the search box, it will turn green. I think it'll be better highlighted.

**Comment by mikelpint** [comment]
Yes, i think so.

**Comment by ZeroDot1** [comment]
#8 
The effects for the search box are ready, try it out.

**Comment by ZeroDot1** [comment]
I have more ideas to improve the design even further, I will implement this step by step if they like it.

**Comment by mikelpint** [comment]
I will create a Gulpfile to make github compile sass automaticaly. This will make the repository lighter and more organised.

**Comment by ZeroDot1** [comment]
I'm working on a new menu
Screenshot:
![bildschirmfoto_2017-11-16_21-55-17](https://user-images.githubusercontent.com/28985171/32915383-fa349352-cb18-11e7-9373-e163fc8b150c.png)

**Comment by mikelpint** [comment]
I will also add a menu for selecting a search engine.

**Comment by ZeroDot1** [comment]
New language menu added #9

**Comment by ZeroDot1** [comment]
That's a good idea :)

**Comment by ZeroDot1** [comment]
with the last updates you deleted the css for the dropdown menu I created, the menu doesn't work as it should anymore, sorry. 
![bildschirmfoto_2017-11-17_00-09-46](https://user-images.githubusercontent.com/28985171/32920934-a88fd51c-cb2b-11e7-96f5-5072ef85575f.png)

**Comment by mikelpint** [comment]
I will fix it later, sorry.

**Comment by mikelpint** [comment]
Fixed, sorry for the inconveniences.

**Comment by mikelpint** [comment]
Is this better?
![captura de pantalla de 2017-11-17 22-14-36](https://user-images.githubusercontent.com/25373557/32969284-c1118d6a-cbe4-11e7-91e8-78808588fbc8.png)

**Comment by ZeroDot1** [comment]
Thanks for the quick fix.
Yes, this is very good :)

**Comment by mikelpint** [comment]
So I will push it.

**Comment by ZeroDot1** [comment]
I have tested the start page with smaller monitors and noticed that it is not compatible, see the screenshot:
![bildschirmfoto_2017-11-17_22-28-11](https://user-images.githubusercontent.com/28985171/32969898-1356dc86-cbe7-11e7-8a18-63b840325b12.png)

**Comment by mikelpint** [comment]
Can you test it, please?

**Comment by ZeroDot1** [comment]
So far everything works, only the view on small monitors is not good. 
![bildschirmfoto_2017-11-17_22-58-52](https://user-images.githubusercontent.com/28985171/32970893-19f6db1e-cbeb-11e7-9f48-8f2e2ae6dbc5.png)

**Comment by mikelpint** [comment]
It should be fixed now.

**Comment by ZeroDot1** [comment]
The footer overlays the other elements, because I did it that way, can you improve it? 
```html
<div align="center" style="position: fixed; left: 0px; bottom: 0px; height: 64px; width: 100%; font-size:10px;">
    <a href="https://github.com/mikelpint/Startpage" target="_blank">GitHub - Startpage</a>
    <p>Translated by: <a href="https://github.com/mikelpint" target="_blank">Mikel Pintado</a></p>
    <br />
  </div>
```

**Comment by ZeroDot1** [comment]
Yes, that's fine with the footer, but now it's shown in the middle of the page when the size of the screen is smaller.  
![bildschirmfoto_2017-11-17_23-24-00](https://user-images.githubusercontent.com/28985171/32971639-6894cf44-cbee-11e7-9784-e744ec86f50a.png)

**Comment by ZeroDot1** [comment]
I've been looking, can these links help?
https://codepen.io/cbracco/pen/zekgx
https://stackoverflow.com/questions/643879/css-to-make-html-page-footer-stay-at-bottom-of-the-page-with-a-minimum-height

**Comment by ZeroDot1** [comment]
![bildschirmfoto_2017-11-17_23-41-16](https://user-images.githubusercontent.com/28985171/32972133-edd66aa8-cbf0-11e7-80a6-382479494bba.png)
![bildschirmfoto_2017-11-17_23-41-51](https://user-images.githubusercontent.com/28985171/32972127-e8e33a80-cbf0-11e7-9ccd-5945b822d250.png)

**Comment by ZeroDot1** [comment]
The look in Chrome and Firefox is different. 
![bildschirmfoto_2017-11-17_23-51-00](https://user-images.githubusercontent.com/28985171/32972365-5914c58e-cbf2-11e7-9ef0-c6de073e6468.png)

**Comment by mikelpint** [comment]
Yes, I know. I'm testing it in my mobile phone with Firefox but it doesn't work.

**Comment by ZeroDot1** [comment]
Hm, try the one from the link.
https://stackoverflow.com/questions/29119290/firefox-footer-with-absolute-position-not-working-no-tables

**Comment by ZeroDot1** [comment]
![bildschirmfoto_2017-11-18_00-10-33](https://user-images.githubusercontent.com/28985171/32972914-00cbd568-cbf5-11e7-9dbe-192d6a1c6683.png)

**Comment by mikelpint** [comment]
We just need to align it at center now.

**Comment by ZeroDot1** [comment]
That looks very good.
![bildschirmfoto_2017-11-18_00-19-54](https://user-images.githubusercontent.com/28985171/32973138-3b4b21ac-cbf6-11e7-8844-eed428b591e3.png)

**Comment by mikelpint** [comment]
Do you want to keep it?

**Comment by ZeroDot1** [comment]
Yes, that's good.

**Comment by mikelpint** [comment]
Ok.

**Comment by mikelpint** [comment]
Well. Goodnight then 😄

**Comment by ZeroDot1** [comment]
I also wish you a good night, Good work:)

**Comment by ZeroDot1** [comment]
New Urls added & Added the category Shopping for the German page
Is the update ok?

**Comment by ZeroDot1** [comment]
@mikelpint 
Please update the style and change it for smaller monitor resolutions and mobile devices.

**Comment by mikelpint** [comment]
The update is very nice.

**Comment by mikelpint** [comment]
Ok, I will fix it.

**Comment by mikelpint** [comment]
It fits well in a 5 inches mobile phone screen.

**Comment by mikelpint** [comment]
Ups. I didn't say nothing xD

**Comment by ZeroDot1** [comment]
I have improved the search, see: #13

**Comment by mikelpint** [comment]
Sorry for not being active.

**Comment by mikelpint** [comment]
I have a lot if exams and I spend the few free I have playing video games.

**Comment by ZeroDot1** [comment]
No problem, Github and the project are still there tomorrow:)

**Comment by ZeroDot1** [comment]
@mikelpint 
Is it possible to add custom scrollbar styling?
https://codepen.io/devstreak/pen/dMYgeO

**Comment by mikelpint** [comment]
I don't know. I will check it.

**Comment by ZeroDot1** [comment]
Thank you :)

**Comment by mikelpint** [comment]
It works in most browsers but it isn't supported by Firefox.

**Comment by ZeroDot1** [comment]
Fiefox is not a browser but an impertinence.
Can you add it so that it is only displayed in the Chrome Browser? that would be great if it would work.

**Comment by ZeroDot1** [comment]
Thanks for adding the scrollbar.
The position of the Google button is fixed, see: #16

**Comment by mikelpint** [comment]
I forgot to push it at 1am xD.

**Comment by ZeroDot1** [comment]
No problem :)

**Comment by mikelpint** [comment]
It is an example scrollbar so it has to be modified.

**Comment by ZeroDot1** [comment]
We just need to add the HTML and JS, then it works.
HTML:
```html
<div id="wrapper">
  <div class="scrollbar" id="style-default">
  <div class="force-overflow"></div>
   </div>
 </div>
```
JS
```js
$(document).ready(function () {
          if (!$.browser.webkit) {
              $('.wrapper').html('<p>Sorry! Non webkit users. :(</p>');
          }
      });
```
CSS
```css
.force-overflow
{
	min-height: 450px;
}

#wrapper
{
	text-align: center;
	width: 500px;
	margin: auto;
}

```

**Comment by ZeroDot1** [comment]
The search does not work correctly if https is not enforced.
I've solved the problem, See: #18

**Comment by ZeroDot1** [comment]
I have created a scrollbar:
![bildschirmfoto_2017-11-25_16-23-08](https://user-images.githubusercontent.com/28985171/33231900-3a727660-d1fd-11e7-9d70-8ee3872802db.png)
```html
  <style>
  ::-webkit-scrollbar-track{
  	-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
  	border-radius: 8px;
  }
::-webkit-scrollbar {
 width: 9px;
 background-color: #2d2d2d;
}
::-webkit-scrollbar-thumb {
  background-image: -webkit-gradient(linear, 0 0, 0 100%,
	                   color-stop(.5, rgba(255, 255, 255, .2)),
					   color-stop(.5, transparent), to(transparent));
 border: 1px dotted red;
 border-radius: 8px;
 background-color: #0ae;
}
::-webkit-scrollbar-thumb:hover {
 background: red;
}
::-webkit-scrollbar-thumb:active {
 background: green;
}
</style>

```

**Comment by ZeroDot1** [comment]
@mikelpint 
How do you think about the idea to add the favicons to the startpage? see the screenshot: 
![bildschirmfoto_2017-12-03_15-56-59](https://user-images.githubusercontent.com/28985171/33526512-f2ad84ae-d842-11e7-9683-0be882ebb1fd.png)

**Comment by mikelpint** [comment]
I think that it it doesn't fit with my objective of a clean design but you can add it to the Deutsch and English pages if you want because it looks nice :D

**Comment by ZeroDot1** [comment]
OK, I'll add it, if you like it you can use it for the Spanish page.

**Comment by mikelpint** [comment]
Ok. Thank you for working on this 😄

**Comment by ZeroDot1** [comment]
I have added favicons to the German page.
You can test it.
https://mikelpint.github.io/Startpage/de.html

**Comment by mikelpint** [comment]
They look very nice.

**Comment by mikelpint** [comment]
I have created a new branch called experiments where we can test our work and do pull requests without overloading this branch.

**Comment by mikelpint** [comment]
I am not very active at working in this webpage because I think that it is pretty stable and that it works fine.

**Comment by ZeroDot1** [comment]
@mikelpint 
I solved the problem that the search entries can't be tracked anymore.
https://github.com/mikelpint/Startpage/commit/b0d09149dd1d23afbeeedcb789cf009bb5f28961

**Comment by mikelpint** [comment]
Oh, thank you. I didn't notice about it.

**Comment by ZeroDot1** [comment]
@mikelpint 
I have added a new category to the German page.
https://github.com/mikelpint/Startpage/commit/51d3f2fdeb24a85ee7e4d7c31c31d5e4a59a1216 
![bildschirmfoto_2018-01-10_16-33-57](https://user-images.githubusercontent.com/28985171/34780897-ab425aea-f624-11e7-9054-4c4d64fd9a2a.png)

**Comment by ZeroDot1** [comment]
I think I also need to update the English site.

**Comment by ZeroDot1** [comment]
@mikelpint I just changed the code of the footer, now we no longer have these scrollbars at the bottom and on the side, I hope you like it.

**Comment by mikelpint** [comment]
Oh, thank you. Good job.

**Comment by ZeroDot1** [comment]
@mikelpint https://github.com/mikelpint/Startpage/commit/befef5cd27c1c33585c8e4c7dc4107596f85fbf5 
With this update I fixed some bugs, now the page loads a bit faster.

**Comment by mikelpint** [comment]
What do you think about the latest commit in the experiments branch?
I did it because the footer was covering some links featured in the lists.

Screenshot:
![screenshot-2018-4-1 inicio](https://user-images.githubusercontent.com/25373557/38173789-f2ed26a2-35c3-11e8-98e0-bc3ad6164d29.png)

**Comment by mikelpint** [comment]
Also, I updated the *experiments* branch

**Comment by ZeroDot1** [comment]
@mikelpint Sorry I'm late answering, I was still busy with my other project.
https://github.com/ZeroDot1/CoinBlockerLists
The Updaes look very good, we should merge them. Good job.
![screencapture-file-home-user-dokumente-github-startpage-de-html-2018-04-01-19_16_45](https://user-images.githubusercontent.com/28985171/38175749-a3daed92-35e1-11e8-8d69-410387c07f9a.png)

**Comment by mikelpint** [comment]
If you noted that the CSS code is ugly that is because I don't write the CSS code directly. I compile the .scss files to the main.css file.

**Comment by mikelpint** [comment]
I write Sass instead of CSS because it helps me to organize code. Also, it provides more features, such as variables.

**Comment by ZeroDot1** [comment]
OK, I didn't think it was ugly, I just ran the beautification through when I checked the code.
I always write everything completely by hand.

**Comment by mikelpint** [comment]
Ok

**Comment by ZeroDot1** [comment]
With the last update I fixed some small bugs. I also changed the link hover color so you can see better which link you are clicking.


Is it a good idea to add Twitter Cards to the startpage?

**Comment by mikelpint** [comment]
Oh, great work. I like the idea of Twitter Cards.

**Comment by ZeroDot1** [comment]
OK, I will add it soon.

**Comment by ZeroDot1** [comment]
@mikelpint Sorry I haven't worked on the site yet to add the Twitter Cards, I haven't been healthy for the last few days, and I have some problems with my computer, my hard drive has broken, and the replacement hard drive I got from recycling isn't working properly either. 
I have a hard drive on my [wish list](https://amzn.to/2IjLcHt) and hope someone can help me.


I have already started working on the Twitter Cards and will upload the update as soon as possible. 

When the Twitter Cards are finished I have to fix some small bugs on the homepage of my project, I hope I can do it all today.
https://zerodot1.github.io/CoinBlockerListsWeb/

**Comment by ZeroDot1** [comment]
@mikelpint I translated the Twitter Card for the Spanish site into Spanish, I hope that's ok.
![bildschirmfoto_2018-05-14_18-54-27](https://user-images.githubusercontent.com/28985171/40011483-416ab30c-57a8-11e8-87f8-341ebcfe71cf.png)
The complete update is ready, look here: https://github.com/mikelpint/Startpage/commit/da220ec3cfde12e1d6f59a8408f8bef18af63310

**Comment by ZeroDot1** [comment]
@mikelpint I have scheduled an update to automatically load the page using the language of the browser. For example, if the user is using a Spanish browser, the Spanish page will be redirected automatically.

What do you think this is a good idea?

**Comment by mikelpint** [comment]
Oh, wonderful ideas. I already knew that German people are very hardworking xD

P. S. Get better if you already haven't.

**Comment by ZeroDot1** [comment]
https://mikelpint.github.io/Startpage/index.html
The update is ready, you can test it, the browser should now do the redirection correctly based on the language of the browser.
I also added the correct lines for the `.htaccess` file, so that it works on any web server if e.g. a user has Javascript disabled. 

Yes, many Germans work very much, but I only work on open source projects, because I can't get any job because of my disabilities.

**Comment by mikelpint** [comment]
What do you think about the latest commit in the experimental branch?
